package org.spring.springboot.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;
@Data
public class CheckDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.id
     *
     * @mbggenerated
     */
    private Integer id;

    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.carType
     *
     * @mbggenerated
     */
    private String cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.carNumber
     *
     * @mbggenerated
     */
    private String carnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.idcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.driverFront
     *
     * @mbggenerated
     */
    private String driverfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.driverBack
     *
     * @mbggenerated
     */
    private String driverback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.idcardFront
     *
     * @mbggenerated
     */
    private String idcardfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.idcarBack
     *
     * @mbggenerated
     */
    private String idcarback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.createTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")

    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table check
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check.id
     *
     * @return the value of check.id
     *
     * @mbggenerated
     */
    private Integer status;
}